### ISSUE TITLE
Start Project with starting page

### ISSUE THREAD

**Issue by kochch1337** [kochch1337/Capstone-Projekt#1]
---
name: Start Project with starting page
about: A classical user story template
title: ''
labels: enhancement
assignees: ''
---
​
## Value Proposition
​
**As a**
User
**I need**
To see the initial data 
​
## Description
When the app starts the data is shown
​
## Acceptance Criteria

- [ ] App starts
- [ ] Data is fetched (dummy Data)
- [ ] Data is shown
​
## Tasks
​
- [ ] Init Projekt
- [ ] Create folders and files
- [ ] Create dummy data
- [ ] Create start page
- [ ] Fetch dummy data
- [ ] Show fetched data on start page
